### ISSUE TITLE
csmake-providers: WgetPicker needs to be more chatty about the URL

### ISSUE THREAD

**Issue by jeremiahpatterson-hpe** [jeremiahpatterson-hpe/csmake#20]
We need to get information from WgetPicker in --verbose (so INFO) about what it's doing with the URL.

**Comment by jerpat-hpe** [comment]
Gh-20: adding an "info" output on pull requests

**Comment by jerpat-hpe** [comment]
Csmake-swak

**Comment by jerpat-hpe** [comment]
https://github.com/jeremiahpatterson-hpe/csmake-swak/pull/1
